version: '3'

services:
  leaderboard.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:1337
      - ConnectionStrings:LeaderboardContext=Server=sql.data;Database=LeaderboardNETCore;User Id=sa;Password=Pass@word;Trusted_Connection=False
    ports:
      - "2000:1337"
    networks:
      - backend
      - frontend
    depends_on:
      - "sql.data"

  gamingwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - LeaderboardWebApiBaseUrl=http://leaderboard.webapi:1337
    ports:
      - "8080:80"
    networks:
      - frontend
    depends_on:
      - "leaderboard.webapi"

  sql.data:
    image: microsoft/mssql-server-linux
    environment:
      - SA_PASSWORD=Pass@word
      - MSSQL_PID=Developer
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge