version: '3'

services:
  leaderboard.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:1337
      - ConnectionStrings:LeaderboardContext=Server=sqldata;Database=LeaderboardNetCore;User Id=sa;Password=Pass@word;Trusted_Connection=False
      - USER_SECRETS_ID=ec3d7cd1-2afd-4080-9128-d320acc85a13
    ports:
      - "1337:1337"
    networks:
      - backend
      - frontend
    volumes:
      - $APPDATA/Microsoft/UserSecrets/$USER_SECRETS_ID:/root/.microsoft/usersecrets/$USER_SECRETS_ID

  gamingwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LeaderboardWebApiBaseUrl=http://leaderboard.webapi:1337
    ports:
      - "8080:80"
    networks:
      - frontend
    depends_on:
      - "leaderboard.webapi"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge