version: '3'

services:
  leaderboard.webapi:
    image: sdp2017/leaderboard.webapi
    build:
      context: ./src/Services/Leaderboard.WebAPI
      dockerfile: Dockerfile

  gamingwebapp:
    image: sdp2017/gamingwebapp
    build:
      context: ./src/Applications/GamingWebApp
      dockerfile: Dockerfile