version: '3'

services:
  leaderboard.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  gamingwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
