version: '3'

services:
  leaderboard.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:1337
      - ConnectionStrings:LeaderboardContext=Server=tcp:sdp2017sql.database.windows.net,1433;Initial Catalog=LeaderboardNetCore;Persist Security Info=False;User ID=sdp2017;Password=abc123!@;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    ports:
      - "1337:1337"
    networks:
      - backend
      - frontend

  gamingwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LeaderboardWebApiBaseUrl=http://leaderboard.webapi:1337
    ports:
      - "8080:80"
    networks:
      - frontend
    depends_on:
      - "leaderboard.webapi"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge